# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jalal's Blog 
email: jalalmostafa22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog. I post stuff I encounter in life wherever
  and whenever they are. You will find science, techology, computer,
  networks and research.
baseurl: "/blog"
url: "jalalmostafa.github.io" # the base hostname & protocol for your site
twitter_username: jalalmostafa22
github_username:  jalalmostafa

# Build settings
markdown: kramdown
